### PR TITLE
Fixed HealThing, added rotation and offset specials

### PR DESCRIPTION
**Pull request by Altazimuth**
Also added Light_MinNeighbor, Polyobj_Stop, and moved functionality out of ev_actions.cpp and into suitable files.

### CODE REVIEW

**Comment by ioan-chera** [comment]
Not sure if HealThing is ready to add. There aren't enough definitions in EE to get max player health regardless of game, and the suggested function uses either the player avatar's max health or some Doom item-specific data.

Sector_SetFloorPanning and SetCeilingPanning are very similar to the Boom trick of using displacement scrollers with instantly moving floors or ceilings to align flats. I'll see if I can combine those specials with Boom's features. Also consider that Boom supports moving things if the floor scrolls. For this case, demo determinism needs to be ensured by carefully getting fixed_t values from the args.

Sector_SetRotation currently has no Boom equivalent, neither graphically nor mechanically.

**Comment by Altazimuth** [comment]
What would you suggest about getting the player avatar's max health? ZDoom doesn't use any methods that are more sophisticated than the ones used in the code, and additionally I didn't want to bloat player_t or add any new EDF fiels (especially without Quasar's permission).

**Comment by ioan-chera** [comment]
I think adding a couple of EDF fields to player class would solve the issue. 0 means raising health to **normal max health**, 1 means to **mega max health** (which is 200 in Doom and Strife I think, 100 in Raven), any other value would be set directly. Maybe Quasar can give more hints on what way is best. Remember if you do so to update the files from base.edf. But he'll probably say he prefers us to focus on UDMF/ZDoom-Hexen integration, THEN on adding new features.

My concern is based on something that doesn't exist in any base game for now: player classes with different max healths. But I can imagine when player classes are fully implemented that players will be able to choose playing from aliens with different health. Adding that will require changing the way item effects are defined...

ZDoom doesn't use any sophisticated checking, but that may be because the function seems ancient, since 1.17, way before Graf Zahl entered or the community matured.

**Comment by Altazimuth** [comment]
Also with regards to a lot of functionality being in EV_Actions (specifically HealThing), I think that changing P_GiveBody to accept Mobjs could work, but refactoring code like that would have to be done extremely carefully as to not break any demo compat, and quite a few demo tests would need to be carried out.

**Comment by Altazimuth** [comment]
I managed to clean up the commits (after wrestling with git). I'm pretty happy with how this all turned out. If you want me to change anything before pulling this then please tell me, and I'll be more than happy to accommodate.

**Pull request merged**
