### PR TITLE
Add support for flatpak

### PR DESCRIPTION
**Pull request by jwoodie**
This PR makes some tweaks that allow for easy flatpak building. I currently have a flatpak-builder file on my system that can be cleaned up and used if this PR is merged.

### CODE REVIEW

**Review by Altazimuth — COMMENTED** [review]
Does the removal of explicit linkage of stdc++fs not break regular Linux linking? I remember at the time it had to be added or else Eternity would not link successfully.

**Comment by jwoodie** [comment]
AFAIK as of C++17 it is required for the std::filesystem stuff to be in libstdc++, I haven't had any issues linking with GCC on my Linux machine.

**Comment by Altazimuth** [comment]
That seems like a good compromise. If you can do that it would be appreciated, thanks.

**Comment by jwoodie** [comment]
Done!

**Comment by Altazimuth** [comment]
Great, thanks. This pull request is greatly appreciated. Does this mean that I should probably make Flatpak builds for releases now?

**Comment by jwoodie** [comment]
Well optimally we would put a flatpak recipe on flathub. It would automatically build the latest available version whenever the recipe is updated.

**Pull request merged**
